#!/usr/bin/env bash
#Debug the nginx server to listen on port 80

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
terminate the first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
