#!/usr/bin/env bash
# Displays "bad luck" in the 4the loop iteration
#+ "good luck" in the 8th
#+ "Best School" in the rest

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "good luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
