#!/usr/bin/env bash
# Displays "bad luck" in the 4the loop iteration
#+ "good luck" in the 8th
#+ "Best School" in the rest

i=1

while [ $i -lt 11 ]; do
	if [ $i -eq 4 ]; then
		echo "good luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
